# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 78c5b61c2c7c644209fe9d6af849f9212d201cdf31f747c6b5ac0d5ebaaa79877c8a4c2b40ca743b914c6d20fbccaac05dfcb598237b063620774adb1c8fb2e7

test:
  secret_key_base: bce6a00ad96f5fdd5224311afd7eb8fbe51ccc7c0b3c67202935c0a9f4e7c00faafb3b40326ebbb4c8cce3c6ad0ff8b25cd7be19e8df48f7f11fddf9d138fcb5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
